### PR TITLE
dialect/sql/schema: disable foreign keys before opening a transaction

### LINKED ISSUE #2954: bug: Atlas Migration and Cascade Delete have unexpected behavior.
Not sure if this belong here or in the Atlas repository, feel free to redirect me! 

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

While generating Versioned Migrations with the new Atlas API, a simple column add results in a breakage of M2M relationships when cascade deletes are enabled. 

## Expected Behavior 🤔

Ent/Atlas should generate migrations that preserve the M2M relationship even when Cascade Delete is enabled. 

## Steps to Reproduce 🕹

Steps:

1. Create Entities with M2M Relationship
2. Generate Initial Migration File
3. Add Data with M2M relationship
4. Add Column to Schema
5. Generate New Migration File
6. Runs Migrations
7. Observe M2M Table is now empty

I don't have time today to put together a minimal reproducible example, but if this is accepted as a valid bug I can work on that in the next couple of days. 

**Here's My Code**

- [Item Entity Schema](https://github.com/hay-kot/homebox/blob/feat/versioned-migrations/backend/ent/schema/item.go)
- [Label Entity Schema](https://github.com/hay-kot/homebox/blob/feat/versioned-migrations/backend/ent/schema/label.go)
- [OnDelete Cascade Option](https://github.com/hay-kot/homebox/blob/d8e4ab7f2dfd5fde39267bc9845a64a8ad6c4854/backend/ent/schema/item.go#L111-L115)
- [Migration File](https://github.com/hay-kot/homebox/blob/feat/versioned-migrations/backend/internal/migrations/migrations/20220924230050_init.sql) when adding a [new field](https://github.com/hay-kot/homebox/blob/feat/versioned-migrations/backend/ent/schema/item.go#L92-L93) to the Item table

When the migration is complete all the Items in the database no longer have any associated Labels. The `label_items` table is empty.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.19 |
| Ent         | 0.11.2   |
| Database    | SQLite   |
| Driver      | github.com/mattn/go-sqlite3     |

### PR DESCRIPTION
**Pull request by masseelch**
Fix #2954

### CODE REVIEW

File: dialect/sql/schema/sqlite.go [hunk 1]
```diff
@@ -6,6 +6,7 @@ package schema
 
 import (
 	"context"
```
Comment (a8m) [inline dialect/sql/schema/sqlite.go:8]: Let’s stay consistent with the current convention: https://github.com/ent/ent/blob/2c63d1d70e6c9ed7648abd1fbfdbfc5a84ff5362/entc/integration/integration_test.go#L9

**Review by a8m — APPROVED** [review]
